---
title: "Schedule"
---

This course will run **Tuesdays from 12:30-3pm in Olsen Hall Rm 234**. Because of holidays / Monday schedules, however, we won’t be meeting every week - see the schedule below for meeting dates and topics.

+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Section              | Date          | Topic                                    | Readings                                                                                                                                                       |
+======================+===============+==========================================+:===============================================================================================================================================================+
| Exp. Success         | January 27th  | Experimental Design                      | Class cancelled due to weather                                                                                                                                 |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exp. Success         | February 3rd  | Data Management                          | Class cancelled due to power outage                                                                                                                            |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exp. Success         | February 10th | Experimental Design & Data Management    | -   [Paper 1 - Cressman & Sharp 2022 (Stats Plans)](materials/readings/Cressman_and_Sharp_2022.pdf)                                                            |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Paper 2 - Marshall 2024 (Experimental Design)](materials/readings/Marshall_2024.pdf)                                                                      |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Paper 3 - Broman & Woo 2018 (Data in Spreadsheets)](materials/readings/Broman_and_Woo_2018.pdf)                                                           |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Paper 4 - Wickham 2014 (Tidy Data)](materials/readings/Wickham_2014.pdf) - Just sections 1 and 2                                                          |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Article - Project Folders in R](https://martinctc.github.io/blog/rstudio-projects-and-working-directories-a-beginner%27s-guide/) - Just skim this article |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Chapter - Frank et al. 2025 (Project Management)](https://experimentology.io/013-management.html)                                                         |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | Other Resources                                                                                                                                                |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Variable Descriptions Excel File](materials/resources/variable_descriptions.xlsx)                                                                         |
|                      |               |                                          | -   A quarto <a href="materials/resources/analysis_plan_template.qmd" download>template analysis plan</a>.                                                     |
|                      |               |                                          | -   [ModernCSV](https://www.moderncsv.com/) (an alternative to Excel for working with CSV files)                                                               |
|                      |               |                                          | -   Another [article](https://www.r-bloggers.com/2018/08/structuring-r-projects-2/) on project folders in R                                                    |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exp. Success         | February 17th | Monday Schedule - No Meeting             |                                                                                                                                                                |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exp. Success         | February 24th | Principles of Statistics / Brainstorming | -   [Paper 1 - Ho et al. 2019 (Estimation Plots)](materials/readings/Ho_etal_2019.pdf)                                                                         |
|                      |               |                                          | -   [Paper 2 - Halsey 2025 (Lack of Effects)](materials/readings/Halsey_2025.pdf)                                                                              |
|                      |               |                                          | -   [Paper 3 - Zuur et al. 2010 (Data Exploration)](materials/readings/Zuur_etal_2010.pdf)                                                                     |
|                      |               |                                          | -   There will be time to brainstorm experimental designs you're thinking about                                                                                |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mixed Effects Models | March 3rd     | Mixed Effects Models                     | -   [Paper 1 - Harrison et al. 2018 (Mixed Effects Models)](materials/readings/Harrison_etal_2018.pdf)                                                         |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Paper 2 - Silk et al. 2020 (Perils and Pitfalls)](materials/readings/silk_etal_2020.pdf)                                                                  |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | -   [Paper 3 - Arnqvist 2020 (Degrees of Freedom)](materials/readings/arnqvist_2020.pdf)                                                                       |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mixed Effects Models | March 10th    | Spring Break - No Meeting                | Install R: [https://cloud.r-project.org](https://cloud.r-project.org/)                                                                                         |
|                      |               |                                          |                                                                                                                                                                |
|                      |               |                                          | Install RStudio: <https://posit.co/download/rstudio-desktop>                                                                                                   |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mixed Effects Models | March 17th    | Mixed Effects Models in R                | -   Data set: [CSV file](materials/resources/dragon_data.csv)                                                                                                  |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mixed Effects Models | March 24th    | Model Interpretation                     |                                                                                                                                                                |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mixed Effects Models | March 31st    | Presentations                            | -   Assignment: [Presentation Information](materials/resources/Presentation_info.pdf)                                                                          |
+----------------------+---------------+------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
